import { BookOpen, ChevronDown, Filter, Flag, Plus } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import type { Chapter, LifeEvent } from '../../types'
import { Empty, formatDay, isoDay, PageIntro, Panel, runAction, splitTags, Tabs, uid, useLocalList, useNowQuery } from './shared'
import type { FeaturePageProps } from './types'

type Scale = 'day' | 'month' | 'year' | 'chapter'
const eventTypes = ['日常', '重要事件', '朋友', '感情', '工作', '学习', '旅行', '游戏', '消费', '成长', '决定', '成就']
function freshEvent(): LifeEvent { return { id: uid('event'), title: '', description: '', date: isoDay(), type: '日常', peopleIds: [], placeIds: [], tags: [], mood: '平静', importance: 50, createdAt: new Date().toISOString() } }
function freshChapter(number: number): Chapter { return { id: uid('chapter'), number, title: '', startDate: isoDay(), description: '', color: '#8b7cff', peopleIds: [], placeIds: [], eventIds: [], song: '', keywords: [] } }

export function TimelinePage({ events: source, chapters: sourceChapters, people = [], places = [], actions }: FeaturePageProps) {
  const [events, setEvents] = useLocalList(source)
  const [chapters, setChapters] = useLocalList(sourceChapters)
  const query = useNowQuery()
  const [scale, setScale] = useState<Scale>('month')
  const [type, setType] = useState('全部')
  const [chapterId, setChapterId] = useState('全部')
  const [editor, setEditor] = useState<'event' | 'chapter' | null>(query.has('new') ? 'event' : null)
  const [eventDraft, setEventDraft] = useState(freshEvent)
  const [chapterDraft, setChapterDraft] = useState(() => freshChapter(chapters.length + 1))
  const [expanded, setExpanded] = useState<string | null>(query.get('id'))
  const visible = useMemo(() => [...events].filter((item) => (type === '全部' || item.type === type) && (chapterId === '全部' || item.chapterId === chapterId)).sort((a, b) => b.date.localeCompare(a.date)), [events, type, chapterId])
  const groups = useMemo(() => {
    const map = new Map<string, LifeEvent[]>()
    visible.forEach((event) => { const key = scale === 'day' ? event.date : scale === 'year' ? event.date.slice(0, 4) : scale === 'chapter' ? chapters.find((item) => item.id === event.chapterId)?.title || '未归档章节' : event.date.slice(0, 7); map.set(key, [...(map.get(key) ?? []), event]) })
    return [...map.entries()]
  }, [visible, scale, chapters])
  const submitEvent = async (event: FormEvent) => { event.preventDefault(); if (!eventDraft.title.trim()) return; await runAction(actions, 'create', 'event', eventDraft); setEvents((items) => [eventDraft, ...items]); setEditor(null); setEventDraft(freshEvent()) }
  const submitChapter = async (event: FormEvent) => { event.preventDefault(); if (!chapterDraft.title.trim()) return; await runAction(actions, 'create', 'chapter', chapterDraft); setChapters((items) => [...items, chapterDraft]); setEditor(null); setChapterDraft(freshChapter(chapters.length + 2)) }

  return <main className="feature-page timeline-page">
    <PageIntro code="LIFE TIMELINE / EVENT STREAM" title="人生时间线" description="以日、月、年或人生章节回看所有重要事件。时间不是列表，而是一条正在展开的故事线。" actions={<><button className="fp-button" onClick={() => setEditor('chapter')}><BookOpen size={15} />新建章节</button><button className="fp-button fp-button--primary" onClick={() => setEditor('event')}><Plus size={15} />记录事件</button></>} />
    <Panel><div className="fp-toolbar"><Tabs value={scale} onChange={setScale} options={[{ value: 'day', label: '日' }, { value: 'month', label: '月' }, { value: 'year', label: '年' }, { value: 'chapter', label: '人生章节' }]} /><div className="timeline-filters"><Filter size={14} /><select className="fp-select" value={type} onChange={(e) => setType(e.target.value)}><option>全部</option>{eventTypes.map((item) => <option key={item}>{item}</option>)}</select><select className="fp-select" value={chapterId} onChange={(e) => setChapterId(e.target.value)}><option value="全部">全部章节</option>{chapters.map((item) => <option value={item.id} key={item.id}>CH.{String(item.number).padStart(2, '0')} {item.title}</option>)}</select></div></div></Panel>
    {chapters.length > 0 && <div className="chapter-strip">{[...chapters].sort((a, b) => a.number - b.number).map((chapter) => <button key={chapter.id} onClick={() => { setScale('chapter'); setChapterId(chapter.id) }} style={{ '--chapter': chapter.color } as React.CSSProperties}><span>CHAPTER {String(chapter.number).padStart(2, '0')}</span><b>{chapter.title}</b><small>{chapter.startDate.slice(0, 4)} — {chapter.endDate?.slice(0, 4) || 'NOW'}</small><i /></button>)}</div>}
    {!visible.length ? <Panel><Empty title={events.length ? '筛选范围内没有事件' : '时间线正在等待第一帧'} description={events.length ? '试着切换事件类型或人生章节。' : '把一个值得记住的片段钉在时间上，它会成为故事的起点。'} action={events.length ? '重置筛选' : '记录第一个事件'} onAction={events.length ? () => { setType('全部'); setChapterId('全部') } : () => setEditor('event')} /></Panel> : <div className="timeline-stream">{groups.map(([key, items]) => <section key={key}><header><span>{key}</span><i /><b>{items.length} EVENT{items.length > 1 ? 'S' : ''}</b></header>{items.map((item) => { const itemPeople = people.filter((person) => item.peopleIds.includes(person.id)); const itemPlaces = places.filter((place) => item.placeIds.includes(place.id)); const open = expanded === item.id; return <article key={item.id} className={open ? 'active' : ''} style={{ '--event-strength': `${item.importance}%` } as React.CSSProperties}><button onClick={() => setExpanded(open ? null : item.id)}><time>{formatDay(item.date)}</time><span className="timeline-marker"><i /></span><div><div className="timeline-event__head"><span className="fp-badge">{item.type}</span><small>{item.mood}</small></div><h3>{item.title}</h3><p>{item.description || item.tags.join(' / ') || '没有补充描述'}</p><div className="fp-chip-list">{item.tags.map((tag) => <span className="fp-chip" key={tag}>{tag}</span>)}{itemPeople.map((person) => <span className="fp-chip active" key={person.id}>@{person.name}</span>)}{itemPlaces.map((place) => <span className="fp-chip" key={place.id}>#{place.name}</span>)}</div></div><ChevronDown size={16} /></button>{open && <div className="timeline-event__detail"><div><b>重要度</b><span className="timeline-strength"><i /></span><em>{item.importance}</em></div><div><b>所属章节</b><span>{chapters.find((chapter) => chapter.id === item.chapterId)?.title || '未归档'}</span></div></div>}</article>})}</section>)}</div>}
    {editor && <div className="fp-popover" onMouseDown={(e) => e.target === e.currentTarget && setEditor(null)}><form className="fp-dialog" onSubmit={editor === 'event' ? submitEvent : submitChapter}><div className="fp-dialog__head"><div><span className="fp-kicker">{editor === 'event' ? 'NEW TIMELINE EVENT' : 'NEW LIFE CHAPTER'}</span><h2>{editor === 'event' ? '记录一个时间节点' : '开启人生章节'}</h2></div><button className="fp-button fp-button--ghost" type="button" onClick={() => setEditor(null)}>取消</button></div>{editor === 'event' ? <EventForm value={eventDraft} setValue={setEventDraft} chapters={chapters} /> : <ChapterForm value={chapterDraft} setValue={setChapterDraft} />}<div className="fp-divider" /><button className="fp-button fp-button--primary" type="submit"><Flag size={15} />写入时间线</button></form></div>}
  </main>
}

function EventForm({ value, setValue, chapters }: { value: LifeEvent; setValue: React.Dispatch<React.SetStateAction<LifeEvent>>; chapters: Chapter[] }) { const set = <K extends keyof LifeEvent>(key: K, next: LifeEvent[K]) => setValue((item) => ({ ...item, [key]: next })); return <div className="fp-form-grid"><label className="fp-field fp-field--wide"><span>事件标题 *</span><input autoFocus required className="fp-input" value={value.title} onChange={(e) => set('title', e.target.value)} /></label><label className="fp-field"><span>日期</span><input className="fp-input" type="date" value={value.date} onChange={(e) => set('date', e.target.value)} /></label><label className="fp-field"><span>类型</span><select className="fp-select" value={value.type} onChange={(e) => set('type', e.target.value)}>{eventTypes.map((item) => <option key={item}>{item}</option>)}</select></label><label className="fp-field"><span>心情</span><input className="fp-input" value={value.mood} onChange={(e) => set('mood', e.target.value)} /></label><label className="fp-field"><span>章节</span><select className="fp-select" value={value.chapterId || ''} onChange={(e) => set('chapterId', e.target.value || undefined)}><option value="">未归档</option>{chapters.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label className="fp-field fp-field--wide"><span>描述</span><textarea className="fp-textarea" value={value.description} onChange={(e) => set('description', e.target.value)} /></label><label className="fp-field"><span>标签</span><input className="fp-input" value={value.tags.join(' ')} onChange={(e) => set('tags', splitTags(e.target.value))} /></label><label className="fp-field"><span>重要度</span><div className="fp-range"><input type="range" min="0" max="100" value={value.importance} onChange={(e) => set('importance', Number(e.target.value))} /><output>{value.importance}</output></div></label></div> }
function ChapterForm({ value, setValue }: { value: Chapter; setValue: React.Dispatch<React.SetStateAction<Chapter>> }) { const set = <K extends keyof Chapter>(key: K, next: Chapter[K]) => setValue((item) => ({ ...item, [key]: next })); return <div className="fp-form-grid"><label className="fp-field"><span>章节编号</span><input className="fp-input" type="number" min="1" value={value.number} onChange={(e) => set('number', Number(e.target.value))} /></label><label className="fp-field"><span>标题 *</span><input autoFocus required className="fp-input" value={value.title} onChange={(e) => set('title', e.target.value)} /></label><label className="fp-field"><span>开始日期</span><input className="fp-input" type="date" value={value.startDate} onChange={(e) => set('startDate', e.target.value)} /></label><label className="fp-field"><span>结束日期</span><input className="fp-input" type="date" value={value.endDate || ''} onChange={(e) => set('endDate', e.target.value || undefined)} /></label><label className="fp-field"><span>主题色</span><input className="fp-input" type="color" value={value.color} onChange={(e) => set('color', e.target.value)} /></label><label className="fp-field"><span>代表歌曲</span><input className="fp-input" value={value.song} onChange={(e) => set('song', e.target.value)} /></label><label className="fp-field fp-field--wide"><span>章节简介</span><textarea className="fp-textarea" value={value.description} onChange={(e) => set('description', e.target.value)} /></label><label className="fp-field fp-field--wide"><span>关键词</span><input className="fp-input" value={value.keywords.join(' ')} onChange={(e) => set('keywords', splitTags(e.target.value))} /></label></div> }

