import type { Rarity } from '../types'
import type { TitleRule } from './models'

type TitleSeed = readonly [
  title: string,
  description: string,
  metric: string,
  value: number,
  rarity?: Rarity,
]

const seeds = [
  ['存档初学者', '你开始认真保存自己的生活。', 'saves', 1],
  ['存档狂魔', '大量日常被你可靠归档。', 'saves', 100, 'RARE'],
  ['时间的装订工', '零散片段在你手里组成书页。', 'saves', 300, 'EPIC'],
  ['连续在线者', '你连续返回人生控制台。', 'saveStreak', 7],
  ['四季不断线', '一整年的信号被稳定接收。', 'saveStreak', 365, 'LEGENDARY'],
  ['夜行动物', '深夜是你熟悉的记录频道。', 'nightSaves', 20, 'UNCOMMON'],
  ['凌晨三点见证者', '大多数人睡去时你仍听见世界。', 'lateNightSaves', 3, 'RARE'],
  ['清晨加载器', '你常在第一束光里启动生活。', 'morningSaves', 20, 'UNCOMMON'],
  ['日出收藏家', '许多个清晨被你留下。', 'morningSaves', 100, 'EPIC'],
  ['雨天观察员', '雨声经常出现在你的档案里。', 'rainSaves', 15, 'UNCOMMON'],
  ['云层译者', '你已记录许多天气的细微差别。', 'weatherVariety', 10, 'RARE'],
  ['城市漫游者', '城市街区持续成为你的支线地图。', 'urbanPlaces', 20, 'RARE'],
  ['坐标点亮者', '你的生活拥有越来越多具体地点。', 'places', 50, 'EPIC'],
  ['地图边缘居民', '你总愿意走向不熟悉的坐标。', 'newPlaces', 30, 'RARE'],
  ['远方采样员', '旅途不断扩大你的世界边界。', 'travelEvents', 20, 'RARE'],
  ['车窗哲学家', '许多思绪发生在移动的风景旁。', 'transitEvents', 30, 'UNCOMMON'],
  ['步行派主角', '你用双脚推进过大量剧情。', 'walkingEvents', 50, 'RARE'],
  ['公园常驻角色', '自然空间是你的稳定恢复点。', 'parkVisits', 30, 'UNCOMMON'],
  ['咖啡店存档员', '咖啡香里保存着多份记录。', 'cafeVisits', 25, 'UNCOMMON'],
  ['书店巡游者', '你在书架间遇见过很多世界。', 'bookstoreVisits', 20, 'RARE'],
  ['支线任务大师', '大量支线已被完整结算。', 'sideQuestsCompleted', 100, 'EPIC'],
  ['主线推进者', '你持续处理那些真正重要的目标。', 'mainQuestsCompleted', 20, 'RARE'],
  ['每日行动派', '微小行动在你手里积少成多。', 'dailyQuestsCompleted', 100, 'RARE'],
  ['随机事件接收器', '你积极响应生活抛来的临时邀请。', 'randomQuestsCompleted', 50, 'RARE'],
  ['任务清空症候群', '清单上的完成标记数量惊人。', 'questsCompleted', 300, 'EPIC'],
  ['低电量英雄', '疲惫时你仍会选择可承受的小任务。', 'tinyQuestsCompleted', 30, 'RARE'],
  ['经验值搬运工', '你把许多具体行动换成了成长。', 'xp', 10000, 'EPIC'],
  ['选择困难症患者', '你认真记录过大量纠结。', 'decisions', 50, 'UNCOMMON'],
  ['理性实验员', '数据与评分经常参与选择。', 'rationalDecisions', 30, 'RARE'],
  ['感性导航员', '你愿意倾听第一反应与身体感受。', 'feelingDecisions', 30, 'RARE'],
  ['长期主义者', '未来价值常进入你的决策模型。', 'longtermDecisions', 30, 'RARE'],
  ['命运投币者', '你时常允许随机打破僵局。', 'fateDecisions', 30, 'RARE'],
  ['YOLO 特派员', '新鲜与刺激在你的选择里有席位。', 'yoloDecisions', 20, 'RARE'],
  ['省事优先协会', '你很懂得为精力预算留余地。', 'easyDecisions', 30, 'UNCOMMON'],
  ['后悔研究员', '你认真回看选择带来的感受。', 'reviewedDecisions', 30, 'RARE'],
  ['果断落子者', '许多选择在短时间内被你确认。', 'fastDecisions', 50, 'RARE'],
  ['硬币看穿者', '投掷前的希望已多次暴露真实倾向。', 'coinRevealMoments', 10, 'EPIC'],
  ['关系图谱编辑', '许多重要角色拥有了清楚档案。', 'people', 30, 'RARE'],
  ['群像剧主角', '你的故事由丰富而真实的人物共同构成。', 'people', 100, 'EPIC'],
  ['长期潜水员', '你保留了不少低频但仍重要的连接。', 'lowFrequencyPeople', 20, 'UNCOMMON'],
  ['社交能量守恒者', '你记录并尊重自己的社交电量。', 'socialEnergyEntries', 50, 'RARE'],
  ['可靠回信人', '你经常主动维护重要连接。', 'contacts', 100, 'RARE'],
  ['纪念日看守', '许多重要日期被你妥善记住。', 'anniversaries', 20, 'RARE'],
  ['共同回忆管理员', '大量事件与人物发生了清楚关联。', 'linkedPeopleEvents', 100, 'EPIC'],
  ['善意翻译器', '你的记录里常出现具体的感谢。', 'gratitudeEntries', 30, 'RARE'],
  ['边界守门员', '你多次为自己的界限留下证明。', 'boundaryEntries', 20, 'RARE'],
  ['重逢触发器', '你记录了许多重新连接的时刻。', 'reunionEvents', 10, 'RARE'],
  ['友情长跑选手', '一段重要友谊跨越了很长时间。', 'longestBondDays', 2000, 'EPIC'],
  ['角色语录收藏家', '你保存了许多让人想起对方的话。', 'peopleQuotes', 50, 'RARE'],
  ['关系星系引力源', '多段深厚关系稳定围绕着你的世界。', 'highBondPeople', 20, 'LEGENDARY'],
  ['电子世界居民', '数字生活是你记录里的重要舞台。', 'digitalEvents', 100, 'RARE'],
  ['屏幕外逃生员', '你多次主动完成无屏幕时段。', 'screenFreeEvents', 30, 'RARE'],
  ['游戏世界旅客', '许多游戏时光成为可回看的记录。', 'gamingEvents', 100, 'RARE'],
  ['音乐场景策展人', '歌曲为你的记忆提供了大量入口。', 'bgmEntries', 100, 'EPIC'],
  ['循环播放体质', '同一首歌陪伴过许多个不同日子。', 'topSongCount', 20, 'UNCOMMON'],
  ['动画片尾幸存者', '你用熟悉故事照顾过很多疲惫夜晚。', 'animeEvents', 30, 'RARE'],
  ['电影感制造者', '平凡画面经常被你发现叙事光泽。', 'cinematicEntries', 30, 'RARE'],
  ['声音采集者', '环境音与对白进入了你的记忆库。', 'audioMemories', 20, 'RARE'],
  ['光影收藏家', '大量照片保存了生活的视觉切片。', 'photos', 200, 'EPIC'],
  ['一帧不漏', '你的相册规模足以组成私人影像史。', 'photos', 1000, 'LEGENDARY'],
  ['天空摄影专员', '天空在你的照片里反复出演。', 'skyPhotos', 50, 'RARE'],
  ['食物先拍协会', '许多味道拥有开动前的证件照。', 'foodPhotos', 50, 'UNCOMMON'],
  ['年度拼贴师', '你用多种素材重组过生活片段。', 'creativeEvents', 50, 'RARE'],
  ['文字炼金术士', '大量生活被转写为自己的语言。', 'storyCharacters', 100000, 'EPIC'],
  ['四行诗供应商', '短诗多次成为今日存档格式。', 'poemEntries', 20, 'RARE'],
  ['梦境编剧', '你把许多梦保存成了可读剧情。', 'dreamEntries', 20, 'RARE'],
  ['灵感急救员', '灵感出现时，你经常及时接住它。', 'inspiredEntries', 30, 'RARE'],
  ['手作支线开启者', '双手完成过一批真实可见的小作品。', 'craftEvents', 20, 'RARE'],
  ['料理实验体', '厨房里发生过大量可食用实验。', 'cookingEvents', 50, 'RARE'],
  ['味觉地图绘制员', '不同食物与店铺组成了你的味觉地图。', 'foodPlaces', 50, 'EPIC'],
  ['早餐剧情派', '一天的开场被你认真对待。', 'breakfastEntries', 30, 'UNCOMMON'],
  ['深夜食堂常客', '许多个夜晚以食物作为温柔收尾。', 'lateMeals', 20, 'UNCOMMON'],
  ['库存拯救专家', '你善于让现有食材找到归宿。', 'pantryQuests', 20, 'RARE'],
  ['甜品回血玩家', '小小甜味多次恢复了今日状态。', 'dessertEntries', 30, 'UNCOMMON'],
  ['饮水提醒已读', '你多次完成了最基础也重要的补给。', 'waterQuests', 50, 'RARE'],
  ['房间刷新者', '居住空间经常被你主动照料。', 'homeCareEvents', 50, 'RARE'],
  ['抽屉终结者', '许多混乱的小空间被逐一攻克。', 'declutterQuests', 30, 'RARE'],
  ['数字园丁', '你的数字空间保持着可呼吸的秩序。', 'digitalCleanups', 50, 'RARE'],
  ['修理支线 NPC', '坏掉的小物常在你手中恢复功能。', 'repairEvents', 20, 'RARE'],
  ['植物监护人', '你持续记录与照料身边的绿色生命。', 'plantEvents', 50, 'RARE'],
  ['床品焕新大使', '干净床铺是你熟悉的恢复魔法。', 'beddingEvents', 20, 'UNCOMMON'],
  ['无痛早睡练习生', '你多次尝试更早结束营业。', 'earlySleepEntries', 20, 'RARE'],
  ['睡眠债务重组师', '休息被你重新放回优先列表。', 'restEntries', 50, 'RARE'],
  ['周末保护协会', '你为不工作与自由时间留下边界。', 'restfulWeekends', 20, 'RARE'],
  ['什么也没做冠军', '你终于多次允许自己不产出。', 'intentionalNothing', 10, 'EPIC'],
  ['情绪天气预报员', '你辨认过许多不同的内在天气。', 'moodsUsed', 20, 'RARE'],
  ['复杂感受容器', '难以命名的心情也能在这里被放下。', 'complexMoodEntries', 20, 'RARE'],
  ['焦虑拆包员', '模糊担忧多次被你拆成具体问题。', 'anxietyReflections', 20, 'RARE'],
  ['小确幸雷达', '你很会接收普通日子里的微弱亮点。', 'positiveEntries', 100, 'EPIC'],
  ['低谷考古学家', '你诚实保存过许多艰难时刻。', 'lowMoodEntries', 50, 'EPIC'],
  ['恢复力采样器', '低落之后的回升被你看见并记录。', 'recoveryEvents', 20, 'RARE'],
  ['自我照顾执行官', '照料自己已经从概念变成行动。', 'selfCareEvents', 100, 'EPIC'],
  ['反内耗工程师', '你学会把责备改写成下一步。', 'selfCompassionEntries', 30, 'RARE'],
  ['人生章节命名者', '多个阶段因你的命名获得轮廓。', 'chapters', 5, 'RARE'],
  ['阶段转换侦察员', '你敏锐捕捉到生活版本的变化。', 'chapters', 10, 'EPIC'],
  ['关键词策展人', '大量词语构成了私人生活索引。', 'uniqueKeywords', 100, 'EPIC'],
  ['年度回看者', '你完整回望过一个年份。', 'yearReviews', 1, 'RARE'],
  ['时间比较学者', '你多次让不同年份彼此对话。', 'lifeCompares', 5, 'RARE'],
  ['过去来信接收人', '记忆胶囊一次次准时抵达。', 'capsulesOpened', 20, 'EPIC'],
  ['未来邮局局长', '你为遥远未来留下大量消息。', 'capsulesCreated', 50, 'EPIC'],
  ['旧日重映员', '往年今日经常被你重新看见。', 'onThisDayViews', 30, 'RARE'],
  ['随机回忆召唤师', '过去的片段被你多次随机唤回。', 'memoryShuffles', 50, 'RARE'],
  ['热力图点灯人', '大量日期在年度图上亮起。', 'activeDays', 200, 'EPIC'],
  ['全年在线', '一年的每个日期都拥有至少一次记录。', 'activeDaysInYear', 365, 'LEGENDARY'],
  ['周五幸运体质', '数据表明周五常给你掉落好心情。', 'happyFridays', 20, 'RARE'],
  ['夏日版本居民', '夏天在你的记录中格外活跃。', 'summerEntries', 100, 'RARE'],
  ['冬夜储存者', '寒冷夜晚被你保存成温暖证据。', 'winterNightEntries', 30, 'RARE'],
  ['秋日关键词猎人', '你尤其擅长捕捉秋天的细节。', 'autumnEntries', 50, 'RARE'],
  ['春季更新包', '新的生长与开始频繁出现在春日档案。', 'springEntries', 50, 'RARE'],
  ['备份偏执者', '你从不让重要记忆只存在一份。', 'exports', 20, 'EPIC'],
  ['本地优先守护者', '你长期维护属于自己的完整数据。', 'dataAgeDays', 365, 'EPIC'],
  ['人生版本管理员', '导入、导出与迁移都在你掌握中。', 'migrations', 5, 'RARE'],
  ['离线也在线', '没有网络时你仍继续记录生活。', 'offlineEntries', 20, 'RARE'],
] satisfies readonly TitleSeed[]

/** 110 条独立称号规则；条件结构可直接交给统计/颁发模块解释。 */
export const titleRules: TitleRule[] = seeds.map((seed, index) => ({
  id: `title-${String(index + 1).padStart(3, '0')}`,
  title: seed[0],
  description: seed[1],
  condition: { metric: seed[2], comparison: 'gte', value: seed[3] },
  rarity: seed[4] ?? 'COMMON',
  priority: index + 1,
}))

export const titles = titleRules
